In [ ]:
import numpy as np
# numerical python
a = np.array([1,2,3,44])
a

array([ 1,  2,  3, 44])

In [ ]:
import pandas as pd
data = pd.DataFrame({
    'a':[1,2,3],
    'b':[4,5,6],
    'c':[4,8,9]
})

In [ ]:
data

a  b  c
0  1  4  4
1  2  5  8
2  3  6  9

In [ ]:
data.values

array([[1, 4, 4],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
nn = np.arange(12).reshape(6,2)
nn

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
nn[0] = 8
nn

array([[ 8,  8],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
a=np.array([2,3,5,6,7,])
a

array([2, 3, 5, 6, 7])

In [ ]:
a[2]=7
a

array([2, 3, 7, 6, 7])

In [ ]:
a.shape

(5,)

In [ ]:
a[:2]
a

array([2, 3, 7, 6, 7])

In [ ]:
h=np.array([[[2,3,4],[3,5,9],[9,8,7]]])
h


array([[[2, 3, 4],
        [3, 5, 9],
        [9, 8, 7]]])

In [ ]:
h.size

9

In [ ]:
h[0][0]

array([2, 3, 4])

In [ ]:
h.ndim

3

In [ ]:
h[0][1]

array([3, 5, 9])

In [ ]:
hello=np.array([[2,3,4],
               [4,5,6],
               [7,8,9]])
hello


array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.argsort(hello)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
np.lexsort(hello)

array([0, 1, 2])

In [ ]:
np.concatenate(hello)

array([2, 3, 4, 4, 5, 6, 7, 8, 9])

In [ ]:
h.flatten()[0:7]

array([2, 3, 4, 3, 5, 9, 9])

In [ ]:
data=np.array([2,3])
data*(1,6)


array([ 2, 18])

In [ ]:
import numpy as ny
xx=ny.array([10,20,30,40])
xx.min()

10

In [ ]:
import numpy as ny
xx=ny.array([10,20,30,40])
xx.max()

40

In [ ]:
import numpy as ny
xx=ny.array([10,20,30,40])
xx.sum(axis=0)

100